import { EmergencyReport } from './types';

export const demoReports: EmergencyReport[] = [
  {
    id: 'RSQ-2024-0847',
    description: 'Multi-vehicle collision on Highway 101 near exit 45. At least 3 vehicles involved, visible injuries, fuel leaking from overturned truck.',
    severity: 'critical',
    services: ['ambulance', 'police'],
    status: 'on-the-way',
    location: 'Highway 101, Mile Marker 45, Northbound',
    victims: 3,
    contact: '+1 (555) 234-5678',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    media: [],
    dispatchMessage: 'CRITICAL ALERT: Multi-vehicle collision on Hwy 101 NB, MM 45. 3+ casualties reported. Fuel leak hazard. Dispatching Ambulance Unit A3 + Traffic Police Unit T7. ETA: 8 minutes.',
    reporterName: 'John Doe',
  },
  {
    id: 'RSQ-2024-0846',
    description: 'Apartment fire on 3rd floor of residential building. Smoke visible from multiple windows. Residents evacuating.',
    severity: 'high',
    services: ['fire', 'ambulance'],
    status: 'dispatched',
    location: '742 Maple Avenue, Apt 3B, Downtown',
    victims: 5,
    contact: '+1 (555) 876-5432',
    timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    media: [],
    dispatchMessage: 'HIGH ALERT: Structure fire at 742 Maple Ave, 3rd floor residential. 5 occupants unaccounted. Fire Unit F2 + Ambulance A1 dispatched. ETA: 6 minutes.',
    reporterName: 'Sarah Chen',
  },
  {
    id: 'RSQ-2024-0845',
    description: 'Break-in reported at electronics store. Suspects fled in dark sedan. Store alarm triggered.',
    severity: 'medium',
    services: ['police'],
    status: 'in-progress',
    location: '1200 Commerce Blvd, Tech Zone Mall',
    victims: 0,
    contact: '+1 (555) 111-2233',
    timestamp: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
    media: [],
    dispatchMessage: 'MEDIUM: Break-in at Tech Zone Mall, 1200 Commerce Blvd. Suspects fled in dark sedan. Police Unit P4 responding.',
    reporterName: 'Mike Johnson',
  },
  {
    id: 'RSQ-2024-0844',
    description: 'Minor fender bender at intersection. No injuries, vehicles blocking right lane.',
    severity: 'low',
    services: ['police'],
    status: 'resolved',
    location: 'Oak Street & 5th Avenue Intersection',
    victims: 0,
    contact: '+1 (555) 444-5566',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    media: [],
    dispatchMessage: 'LOW: Minor traffic incident at Oak St & 5th Ave. No injuries. Traffic control requested.',
    reporterName: 'Emily Davis',
  },
  {
    id: 'RSQ-2024-0843',
    description: 'Suspicious individual loitering near school entrance after hours. Wearing dark clothing and carrying a large bag.',
    severity: 'medium',
    services: ['police'],
    status: 'received',
    location: 'Lincoln Elementary, 4th Street',
    victims: 0,
    contact: '+1 (555) 999-8888',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    media: [],
    dispatchMessage: 'MEDIUM: Suspicious activity at Lincoln Elementary. Unit P12 dispatched for welfare check.',
    reporterName: 'George Miller',
  },
];

export const demoPresets = [
  {
    name: '🚗 Road Accident',
    description: 'A severe two-car collision at the intersection of Main Street and Oak Avenue. One vehicle overturned. Multiple passengers appear injured. Traffic is completely blocked in both directions.',
    services: ['ambulance', 'police'] as const,
    severity: 'high' as const,
    victims: 2,
    location: 'Main Street & Oak Avenue Intersection',
    contact: '+1 (555) 999-0001',
  },
  {
    name: '🔥 Building Fire',
    description: 'Heavy smoke and flames visible from the 4th floor of a 6-story apartment building. Fire alarms sounding throughout. Residents evacuating via fire escapes. At least 5 people may still be inside.',
    services: ['fire', 'ambulance'] as const,
    severity: 'critical' as const,
    victims: 5,
    location: '500 Pine Road, Downtown District',
    contact: '+1 (555) 999-0002',
  },
  {
    name: '🚨 Theft Report',
    description: 'Witnessed an armed robbery at the corner convenience store. Two suspects wearing dark hoodies fled on foot heading east toward the park. Store owner may need medical attention.',
    services: ['police'] as const,
    severity: 'medium' as const,
    victims: 1,
    location: '8th Street Convenience Store',
    contact: '+1 (555) 999-0003',
  },
  {
    name: '🏥 Medical Emergency',
    description: 'Elderly neighbor appears to be having a stroke. Slurred speech and facial drooping. Sudden onset about 10 minutes ago.',
    services: ['ambulance'] as const,
    severity: 'critical' as const,
    victims: 1,
    location: '212 West Oak Lane',
    contact: '+1 (555) 999-0004',
  },
];
